api = 2
core = 7.x
projects[designssquare_com_module_calypso][type] = "module"
projects[designssquare_com_module_calypso][subdir] = contrib
projects[designssquare_com_module_calypso][version] = 7.x-1.0
projects[designssquare_com_module_calypso][download][type] = "git"
projects[designssquare_com_module_calypso][download][url] = "https://github.com/kapasoft-drupal-modules/calypso.git"
projects[designssquare_com_module_calypso][download][branch] = "master"
;;widget[0][name]=designssquare_com_module_calypso_structure
;;widget[0][order]=1
;;widget[1][name]=designssquare_com_module_calypso_data
;;widget[1][order]=2
projects[designssquare_com_theme_calypso][type] = "theme"
projects[designssquare_com_theme_calypso][version] = 7.x-1.0
projects[designssquare_com_theme_calypso][download][type] = "git"
projects[designssquare_com_theme_calypso][download][url] = "https://github.com/kapasoft-drupal-themes/calypso.git"
projects[designssquare_com_theme_calypso][download][branch] = "master"
projects[bootstrap][type] = "theme"
projects[bootstrap][version] = 7.x-1.0
projects[bootstrap][download][type] = "git"
projects[bootstrap][download][url] = "https://github.com/kapasoft-drupal-themes/bootstrap.git"
projects[bootstrap][download][branch] = "master"
