api = 2
core = 7.x
projects[designssquare_com_blog][type] = "module"
projects[designssquare_com_blog][subdir] = contrib
projects[designssquare_com_blog][version] = 7.x-1.0
projects[designssquare_com_blog][download][type] = "git"
projects[designssquare_com_blog][download][url] = "http://github.com/kapasoft-drupal-modules/blog.git"
projects[designssquare_com_blog][download][branch] = "master"
widget[0][name]=designssquarecom_blog_structure
widget[0][order]=1
widget[1][name]=designssquarecom_blog_example_data
widget[1][order]=2
widget[2][name]=designssquare_com_blog
widget[2][order]=0
