api = 2
core = 7.x
projects[drupal][type] = core
projects[drupal][version] = 7.26
projects[] = jquery_update
projects[] = module_filter
projects[] = diff
projects[] = devel_themer
projects[] = coffee
projects[] = admin_menu
projects[] = features_diff
projects[] = pathauto
projects[] = menu_html
projects[] = token

projects[] = context
projects[] = ctools
projects[] = features
projects[] = features_extra
projects[] = strongarm
projects[uuid][version] = 1.x-dev
projects[uuid_features][version] =1.x-dev
projects[] = views
projects[] = entity
projects[] = entityreference
