api = 2
core = 7.x
projects[designssquare_com_theme_cascade][type] = "module"
projects[designssquare_com_theme_cascade][subdir] = contrib
projects[designssquare_com_theme_cascade][version] = 7.x-1.0
projects[designssquare_com_theme_cascade][download][type] = "git"
projects[designssquare_com_theme_cascade][download][url] = "git@github.com-kapasoft-drupal-modules:kapasoft-drupal-modules/theme_cascade.git"
projects[designssquare_com_theme_cascade][download][branch] = "master"
widget[0][name]=designssquare_com_theme_cascade_structure
widget[0][order]=1
widget[1][name]=designssquare_com_theme_cascade_data
widget[1][order]=2
widget[2][name]=designssquare_com_menu_importer_cascade
widget[2][order]=3
projects[cascade][type] = "theme"
projects[cascade][version] = 7.x-1.0
projects[cascade][download][type] = "git"
projects[cascade][download][url] = "git@github.com-kapasoft-drupal-themes:kapasoft-drupal-themes/theme_cascade.git"
projects[cascade][download][branch] = "master"
